language: perl6

os:
  - linux
  - osx

perl6:
  - latest

sudo: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install primesieve; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install primesieve; fi

install:
  - rakudobrew build zef
  - zef install .
